### ISSUE TITLE
Foreign key error

### ISSUE THREAD

**Issue by keithslater** [kjdion84/turtle#1]
php artisan migrate

Migration table created successfully.

  [Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `role_user` add constraint `role_user_role_id_foreign` foreign key (`role_id`) references `roles` (`id`) on de
  lete cascade)

  [PDOException]
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint

**Comment by kjdion84** [comment]
What version of MySQL?

**Comment by keithslater** [comment]
5.6.34

**Comment by kjdion84** [comment]
I believe this is because the migrations are not using `unsigned()` for the foreign key integers. Updating code now!

**Comment by kjdion84** [comment]
I went ahead and just pushed 1.0.8. Please give packagist a few mins to update, then run `composer update` and the migrations for your version of MySQL should work.

**Comment by keithslater** [comment]
That did it, thanks.
