### ISSUE TITLE
Demo mode

### ISSUE THREAD

**Issue by soyraro** [kjdion84/turtle#2]
Hi.. I have setup your application but cant change from demo mode to normal mode... cant update records.
Thanks for your work

**Comment by kjdion84** [comment]
Make sure you followed this installation thoroughly.

Then change `demo_mode` to `false` in `config/turtle.php`.

**Comment by soyraro** [comment]
Installation followed... I havent done the recommended though

demo_mode is in false

Not working

Thanks

**Comment by kjdion84** [comment]
Then something else is the issue. Open up Chrome developer tools and look at the Network tab. Tell me what errors you get from any of the requests.

**Comment by soyraro** [comment]
I dont know but now Im getting in a browser window when i try to list the users:

DataTables warning: table id=users_datatable - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

**Comment by kjdion84** [comment]
Please run composer update, there was a change to data tables recently which effected my package. I already released a fix.

**Comment by soyraro** [comment]
Ok... now works!!! thanks for your job
