### ISSUE TITLE
How to use own resource views instead of package default?

### ISSUE THREAD

**Issue by bruno-farias** [kjdion84/turtle#3]
I have published the views to my /resources folder, but it still serve the packages view to home and others views.

**Comment by bruno-farias** [comment]
I managed to make work:
- Created a new Controller extending Kjdion84\Turtle\Controllers\AppController;
- Override home method to render the correct view;
- On turtle config, on controllers section changed app to use the created controller
- profit

**Comment by kjdion84** [comment]
Yep, that is the correct approach :)

**Comment by kjdion84** [comment]
Just FYI the views issue mentioned is fixed in the latest release (v 1.1.0).
