### ISSUE TITLE
Migrating tables... a question

### ISSUE THREAD

**Issue by soyraro** [kjdion84/turtle#4]
Hi kjdion84
I dont see the point to publish the migrations because every time you do php artisan migrate the migration executed are from the vendor folder, not the migrations folder. Or am I missing something?

And if your application name is different than 'App'. Console says
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'App\User' not found

Obviously because the migrations in the vendor folder use App User

And how Laravel can use the views published? 

Thanks for your amazing work

**Comment by kjdion84** [comment]
Yep there seems to be a bug with the publishing stuff, even the published views dont work properly.

I'll be fixing these issues including the App\User in the next release.

**Comment by kjdion84** [comment]
I just release `1.1.0` which addresses all of these issues :)
