### ISSUE TITLE
Fail after composer update

### ISSUE THREAD

**Issue by soyraro** [kjdion84/turtle#5]
Didnt work after composer update.
Removed turtle
Composer update
Added again by composer require, would be nice if you require an users database created before installing turtle in your setup instructions and if exists recreate before installation.

php artisan migrate

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Illuminate\Foundation\Application::create()

**Comment by kjdion84** [comment]
The whole thing revolves around laravels built in auth. So you need to have the user tables already implemented.
