### ISSUE TITLE
Question, how to insert my own script?

### ISSUE THREAD

**Issue by Majunko** [kjdion84/turtle#9]
Hi, 

I create a new .js file and i include on my **index view**, inside `@push('scripts')`
something like
```
@push('scripts')
<script src="{{ asset('vendor/flexdatalist/jquery.flexdatalist.min.js') }}"></script>
<script src="{{ asset('js/custom.js') }}"></script>
@endpush
```
Inside of this file i want to use this jquery script [http://projects.sergiodinislopes.pt/flexdatalist/](url) to create a dynamic select.

File **custom.js**
```
$(document).on('click', '[data-modal]', function (event) {
    event.preventDefault();

    mydata = [
        {"id":"47", "name":"Colombia", "capital": "Bogota"}
    ];

    $("#country").flexdatalist({
        minLength: 0,
        valueProperty: '*',
        selectionRequired: true,
        searchDelay: 400,
        visibleProperties: ["name", "capital"],
        searchIn: ['name', 'capital'],
        data: mydata,
        noResultsText: 'No results for "{keyword}"'
    });
});
```
it doesn't insert any data and doesn't initialize the script, but if i insert this script on the console of browser it works.

Input on **add.blade.php**
```
<div class="form-group form-group-sm col-sm-6">
   <div class="row">
      {!! Form::label('country','Country:', ['class'=> 'col-sm-3 col-form-label']) !!}
      <div class="col-sm-5 col-md-8">
         {!! Form::text('country', null, ['class'=>'form-control flexdatalist', 'placeholder'=>'Choose one...']) !!}
      </div>
   </div>
</div>
```

Any idea? Thanks.

**Comment by kjdion84** [comment]
You need to cal the javascript code inside `ajaxComplete` not `click` since the modals use AJAX to display.

    $(document).ajaxComplete(function () {
        mydata = [
            {"id":"47", "name":"Colombia", "capital": "Bogota"}
        ];

        $("#country").flexdatalist({
            minLength: 0,
            valueProperty: '*',
            selectionRequired: true,
            searchDelay: 400,
            visibleProperties: ["name", "capital"],
            searchIn: ['name', 'capital'],
            data: mydata,
            noResultsText: 'No results for "{keyword}"'
        });
    });

**Comment by Majunko** [comment]
Thank you!!

**Comment by Majunko** [comment]
Another question, if i want to do a query by method ajax, it will being in an infinite loop, how can i to handle it ?

```
$(document).ajaxComplete(function (event) {
    event.preventDefault();

    $.ajax({
        method: "GET",
        url: "/" + "country",
        dataType: "json",
        data: "",
        error: function() {
          alert("Error");
      },
      success: function(mydata) {
          $("#country").flexdatalist({
            minLength: 0,
            valueProperty: '*',
            selectionRequired: true,
            searchDelay: 400,
            visibleProperties: ["name", "capital"],
            searchIn: ['name', 'capital'],
            data: mydata,
            noResultsText: 'No results for "{keyword}"'
        });

      }
  });
});
```
Another way to do something like that? Thanks.

**Comment by kjdion84** [comment]
Perform that ajax request outside of ajaxComplete. Set a global variable outside of ajaxComplete, and set it using that ajax call. Then in your ajaxComplete method simply use that variable (mydata).

**Comment by Majunko** [comment]
Yeah, it works very well thanks again for taking your time and Thank you for development this great project.
Regards.
